export const REMOTE_COMMANDS_DISABLED =
  process.env.REMOTE_COMMANDS_ENABLED !== "true";

export const ACTIVE_COMMAND_POLL_AFTER_SECONDS = 6;
export const SUSPENDED_COMMAND_POLL_AFTER_SECONDS = 300;
