export const REMOTE_COMMANDS_ENABLED =
  process.env.REMOTE_COMMANDS_ENABLED === "true";

export const REMOTE_COMMANDS_DISABLED = !REMOTE_COMMANDS_ENABLED;

export const ACTIVE_COMMAND_POLL_AFTER_SECONDS = 6;
export const SUSPENDED_COMMAND_POLL_AFTER_SECONDS = 300;
